DROP TABLE COFFEE_ORDER;

CREATE TABLE COFFEE_ORDER(
	ORDERCOUNT NUMBER(4) NOT NULL,
	-- 주문번호
	USERID   VARCHAR2 (30) NOT NULL, 
	-- member 테이블과 조인 
	COFFEENAME VARCHAR2(50) NOT NULL,
	-- coffeeMEM 테이블과 조인 
	WDATE DATE ,
	-- 주문한 시간 
	SYRUP NUMBER(1),
	-- 시럽 추가여부 
	WHIPPING NUMBER(1),
	-- 휘핑 추가여부 
	CSIZE VARCHAR2(20) NOT NULL,
	-- coffeeMEM 테이블에서 가격을 가져오기위한 컬럼
	AMOUNT NUMBER(3) NOT NULL,
	-- 갯수를 저장할 컬럼 
	TOTAL NUMBER(10) NOT NULL
	-- 총 금액 
);

ALTER TABLE COFFEE_ORDER
ADD CONSTRAINT FK_ORDER_ID FOREIGN KEY (USERID) 
REFERENCES MEMBER(ID);